Repository Spring-Cooler/SGMA_Backend, pull requests merged in 2024-09, with the labels that each got.

#94 Feat: 스터디그룹원 회원별 조회 API 추가
  src/main/java/com/springcooler/sgma/studygroupmember/query/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceImpl.java
  src/main/resources/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.xml
  src/test/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceTests.java
Labels: enhancement

#98 Refactor: user 도메인 json형식 수정 및 시간 타입 변경
  src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/UserEntity.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/RequestUpdateUserVO.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/ResponseUserVO.java
  src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/query/dto/RecruitmentBoardCommentDTO.java
  src/main/java/com/springcooler/sgma/user/query/dto/RecruitmentBoardReplyDTO.java
  src/main/java/com/springcooler/sgma/user/query/dto/UserDTO.java
  src/main/java/com/springcooler/sgma/user/query/service/RecruitmentCommentServiceImpl.java
  src/main/java/com/springcooler/sgma/user/query/service/UserService.java
  src/main/java/com/springcooler/sgma/user/query/service/UserServiceImpl.java
  src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTests.java
  src/test/java/com/springcooler/sgma/user/query/service/UserServiceImplTests.java
Labels: enhancement

#101 스터디 그룹 지원 신청 및 지원 신청 취소
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/controller/RecruitmentBoardCommandController.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/aggregate/StudyGroupApplicantId.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantCommandController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
Labels: bug, documentation

#103 Refactor: 회원 프로필의 이미지를 S3에 업로드로 수정
  build.gradle
  src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/command/application/dto/RequestUpdateUserDTO.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  src/main/java/com/springcooler/sgma/user/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/user/config/S3Config.java
  src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTests.java
Labels: enhancement

#104 Feat: Submitted Answer DML Defaults
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/command/domain/repository/ProblemRepository.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/DomainProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/SubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/SubmittedAnswerPK.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/repository/SubmittedAnswerRepository.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/service/DomainSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerServiceImpl.java
  src/test/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceTests.java
  src/test/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceTests.java
  src/test/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerServiceTests.java
Labels: enhancement

#105 Feat: 스터디 그룹 승인 요청 #102
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantCommandController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/repository/StudyGroupApplicantRepository.java
Labels: enhancement

#106 Fix: User도메인 S3라이브러리 주석 처리
  src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  src/main/java/com/springcooler/sgma/user/config/S3Config.java
Labels: bug

#110 Fix: UserServiceImplTests 주석 처리
  src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTests.java
Labels: enhancement

#109 Feat: 일정 생성, 수정 일정 참가, 참가취소 기능 추가
  src/main/java/com/springcooler/sgma/studyschedule/command/application/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/dto/StudyScheduleDTO.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/aggregate/StudySchedule.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/repository/StudyScheduleRepository.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/infrastructure/service/InfraStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/infrastructure/service/InfraStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/dto/StudyScheduleParticipantDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/aggregate/StudyScheduleParticipant.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/repository/StudyScheduleParticipantRepository.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/service/DomainStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/service/DomainStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/config/StudyScheduleParticipantMybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/dto/StudyScheduleParticipantDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/repository/StudyScheduleParticipantMapper.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/service/StudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/service/StudyScheduleParticipantServiceImpl.java
  src/main/resources/com/springcooler/sgma/studyscheduleparticipant/query/repository/StudyScheduleParticipantMapper.xml
Labels: enhancement

#111 Feat: 선지 Select + DML 기본
  src/main/java/com/springcooler/sgma/choice/command/application/dto/ChoiceDTO.java
  src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceService.java
  src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceImpl.java
  src/main/java/com/springcooler/sgma/choice/command/application/service/ChoiceService.java
  src/main/java/com/springcooler/sgma/choice/command/domain/aggregate/Choice.java
  src/main/java/com/springcooler/sgma/choice/command/domain/aggregate/ChoicePK.java
  src/main/java/com/springcooler/sgma/choice/command/domain/repository/ChoiceRepository.java
  src/main/java/com/springcooler/sgma/choice/common/ResponseDTO.java
  src/main/java/com/springcooler/sgma/choice/common/exception/CommonException.java
  src/main/java/com/springcooler/sgma/choice/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/choice/common/exception/ExceptionDTO.java
  src/main/java/com/springcooler/sgma/choice/common/exception/GlobalExceptionHandler.java
  src/main/java/com/springcooler/sgma/choice/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/choice/query/controller/ChoiceController.java
  src/main/java/com/springcooler/sgma/choice/query/dto/ChoiceDTO.java
  src/main/java/com/springcooler/sgma/choice/query/repository/ChoiceMapper.java
  src/main/java/com/springcooler/sgma/choice/query/service/ChoiceService.java
  src/main/java/com/springcooler/sgma/choice/query/service/ChoiceServiceImpl.java
  src/main/resources/com/springcooler/sgma/choice/ChoiceMapper.xml
  src/main/resources/com/springcooler/sgma/choice/query/repository/ChoiceMapper.xml
  src/test/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceTests.java
  src/test/java/com/springcooler/sgma/choice/query/service/ChoiceServiceTests.java
  src/test/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceTests.java
Labels: enhancement

#114 Refactor: 바뀐 DB 모델링 반영
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/query/dto/StudyGroupDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/GroupRole.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMember.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/dto/StudyGroupMemberDTO.java
  src/main/resources/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.xml
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupcategory/command/application/service/StudyGroupCategoryTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#115 Feature/study shedule
  src/main/java/com/springcooler/sgma/studyschedule/command/application/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/dto/StudyScheduleDTO.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/aggregate/StudySchedule.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/aggregate/StudyScheduleStatus.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/infrastructure/service/InfraStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/infrastructure/service/InfraStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/dto/StudyScheduleDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/dto/StudyScheduleParticipantDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/repository/StudyScheduleParticipantRepository.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/dto/StudyScheduleParticipantDTO.java
  src/main/resources/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleMapper.xml
  src/main/resources/com/springcooler/sgma/studyscheduleparticipant/query/repository/StudyScheduleParticipantMapper.xml
Labels: enhancement

#120 Feat: 스터디그룹원 응답 데이터 닉네임 추가
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMember.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/dto/StudyGroupNoticeDTO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/StudyGroupNotice.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/dto/StudyGroupNoticeDTO.java
  src/main/resources/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.xml
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
Labels: enhancement

#122 Refactor: 스터디 그룹 일정 단건 조회 기능 수정
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleMapper.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/repository/StudyScheduleParticipantRepository.java
Labels: enhancement

#126 Fix: 테스트코드 println -> log.info 변경
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupcategory/command/application/service/StudyGroupCategoryTests.java
  src/test/java/com/springcooler/sgma/studygroupcategory/query/service/StudyGroupCategoryTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#123 Feat: 시험평균, 표준편차 기능 추가, 출제완료여부 기능 추가, 테스트코드 일부 추가
  src/main/java/com/springcooler/sgma/studyschedule/command/application/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleMapper.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/repository/StudyScheduleParticipantRepository.java
  src/test/java/com/springcooler/sgma/studySchedule/command/application/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studySchedule/query/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studyScheduleParticipant/command/application/service/StudyScheduleParticipantServiceTests.java
  src/test/java/com/springcooler/sgma/studyScheduleParticipant/query/service/StudyScheduleParticipantServiceTests.java
Labels: enhancement

#130 Fix: Applicant GroupId 타입 이슈 해결 #102
  src/main/java/com/springcooler/sgma/recruitmentboard/batch/BatchScheduler.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/repository/RecruitmentBoardRepository.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/service/StudyGroupApplicantDomainService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/infrastructure/service/StudyGroupApplicantService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/dto/RecruitmentBoardCommentCommandDTO.java
  src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/service/RecruitmentBoardCommentCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
Labels: bug

#131 Refactor: 어노테이션 추가 및 코드 분리
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/service/RecruitmentBoardCommentCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
Labels: enhancement

#132 Fix: 버그 수정
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/query/controller/ProblemController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  src/test/java/com/springcooler/sgma/problem/query/service/ProblemServiceTests.java
Labels: bug

#133 Refactor: 반환형 Entity -> DTO 변경
  src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/StudyGroup.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/application/controller/StudyGroupCategoryController.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/application/service/AppStudyGroupCategoryService.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/application/service/AppStudyGroupCategoryServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/domain/aggregate/StudyGroupCategory.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMember.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/StudyGroupNotice.java
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupcategory/command/application/service/StudyGroupCategoryTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#135 Refactor: 전체 수정
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/application/service/AppStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/aggregate/RestStatus.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/aggregate/StudySchedule.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/command/domain/service/DomainStudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/command/infrastructure/service/InfraStudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/common/ResponseDTO.java
  src/main/java/com/springcooler/sgma/studyschedule/common/exception/CommonException.java
  src/main/java/com/springcooler/sgma/studyschedule/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/studyschedule/common/exception/ExceptionDTO.java
  src/main/java/com/springcooler/sgma/studyschedule/common/exception/StudyScheduleExceptionHandler.java
  src/main/java/com/springcooler/sgma/studyschedule/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/aggregate/RestStatus.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/aggregate/StudyScheduleParticipant.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/repository/StudyScheduleParticipantRepository.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/service/DomainStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/domain/service/DomainStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/common/ResponseDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/common/exception/CommonException.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/common/exception/ExceptionDTO.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/common/exception/StudyScheduleParticipantExceptionHandler.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/query/service/StudyScheduleParticipantServiceImpl.java
  src/test/java/com/springcooler/sgma/studyScheduleParticipant/command/application/service/StudyScheduleParticipantServiceTests.java
  src/test/java/com/springcooler/sgma/studyschedule/command/application/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/StudyScheduleParticipantServiceTests.java
  src/test/java/com/springcooler/sgma/studyscheduleparticipant/query/service/StudyScheduleParticipantServiceTests.java
Labels: enhancement

#137 Feature/study shedule
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/repository/SubmittedAnswerRepository.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerServiceImpl.java
Labels: enhancement

#140 Feature/study shedule
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/AppStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/infrastructure/service/InfraStudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/repository/SubmittedAnswerRepository.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerServiceImpl.java
Labels: enhancement

#141 Refactor: 빌더 패턴 도입
  src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/dto/StudyGroupDTO.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/vo/RequestStudyGroupVO.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/vo/ResponseStudyGroupVO.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/application/controller/StudyGroupCategoryController.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/application/dto/StudyGroupCategoryDTO.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/domain/aggregate/vo/RequestStudyGroupCategoryVO.java
  src/main/java/com/springcooler/sgma/studygroupcategory/command/domain/aggregate/vo/ResponseStudyGroupCategoryVO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/vo/RequestStudyGroupMemberVO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/vo/ResponseStudyGroupMemberVO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/dto/StudyGroupNoticeDTO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/vo/RequestStudyGroupNoticeVO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/vo/ResponseStudyGroupNoticeVO.java
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupcategory/command/application/service/StudyGroupCategoryTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
  src/test/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/StudyScheduleParticipantServiceTests.java
Labels: enhancement

#142 Feature/study shedule
  src/main/java/com/springcooler/sgma/studyscheduleparticipant/command/application/controller/StudyScheduleParticipantController.java
  src/test/java/com/springcooler/sgma/studyschedule/command/application/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/studyscheduleparticipant/command/application/service/StudyScheduleParticipantTests.java
  src/test/java/com/springcooler/sgma/studyscheduleparticipant/query/service/StudyScheduleParticipantTests.java
Labels: enhancement

#147 DTO 및 쿼리 수정
  src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#148 fix: Response type 수정
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/controller/RecruitmentBoardCommandController.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/controller/RecruitmentBoardCommentCommandController.java
  src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/controller/RecruitmentBoardCommentController.java
  src/main/java/com/springcooler/sgma/recruitmentboardreply/query/controller/RecruitmentBoardReplyController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantCommandController.java
Labels: documentation

#152 Test: 테스트 코드 수정
  src/test/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceTests.java
  src/test/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceTests.java
  src/test/java/com/springcooler/sgma/recruitmentboard/command/application/service/StudyGroupApplicantCommandServiceTests.java
  src/test/java/com/springcooler/sgma/studyschedule/command/application/service/StudyScheduleServiceTests.java
  src/test/java/com/springcooler/sgma/user/query/service/UserServiceImplTests.java
Labels: bug

#161 Refactor: PathVariable 명시
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/command/application/controller/StudyGroupCategoryController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/query/controller/StudyGroupCategoryController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/query/controller/StudyGroupMemberController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
Labels: enhancement

#162 Refactor: 타입 primitive -> reference 변경
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/command/domain/aggregate/StudyGroupCategory.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.java
Labels: enhancement

#163 Refactor: 스터디 모집글 Migration
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/config/MybatisConfiguration.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/common/exception/CommonException.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/config/MybatisConfiguration.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/controller/RecruitmentBoardCommentController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/dto/RecruitmentBoardCommentDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/repository/RecruitmentBoardCommentMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/service/RecruitmentBoardCommentService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/config/MybatisConfiguration.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/controller/RecruitmentBoardReplyController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/dto/RecruitmentBoardReplyDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/service/RecruitmentBoardReplyService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/common/exception/ErrorCode.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/config/MybatisConfiguration.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/controller/StudyGroupApplicantController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/dto/StudyGroupApplicantDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/service/StudyGroupApplicantService.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardcomment/query/repository/RecruitmentBoardCommentMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.xml
  MSA/Recruitment/src/test/java/com/springcooler/sgma/recruitmentboard/query/service/StudyGroupApplicantServiceTests.java
Labels: enhancement

#166 JsonProperty -> JsonNaming으로 수정 #165
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/application/dto/RecruitmentBoardCommandDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/dto/RecruitmentBoardCommentCommandDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/dto/RecruitmentBoardCommentDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/common/ResponseDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/command/application/dto/RecruitmentBoardReplyDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/dto/RecruitmentBoardReplyDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantCommandDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/vo/RequestStudyGroupMemberVO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/dto/StudyGroupApplicantDTO.java
Labels: enhancement

#176 Feat: 스터디그룹 자유게시판 게시글 기능 구현, 댓글 조회 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/dto/StudyGroupBoardDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/aggregate/RestStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/aggregate/StudyGroupBoard.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/aggregate/StudyGroupBoardStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/aggregate/vo/RequestStudyGroupBoardVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/aggregate/vo/ResponseStudyGroupBoardVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/repository/StudyGroupBoardRepository.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/service/DomainStudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/domain/service/DomainStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/common/ResponseDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/common/exception/CommonException.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/common/exception/ErrorCode.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/common/exception/ExceptionDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/common/exception/StudyGroupBoardGlobalExceptionHandler.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/config/MybatisConfiguration.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/dto/StudyGroupBoardDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/controller/StudyGroupBoardCommentController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/dto/StudyGroupBoardCommentDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/AppStudyGroupBoardCommentService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/AppStudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/aggregate/RestStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/aggregate/StudyGroupBoardComment.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/aggregate/StudyGroupBoardCommentStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/aggregate/vo/RequestStudyGroupBoardCommentVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/aggregate/vo/ResponseStudyGroupBoardCommentVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/repository/StudyGroupBoardCommentRepository.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/service/DomainStudyGroupBoardCommentService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/service/DomainStudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/common/ResponseDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/common/exception/CommonException.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/common/exception/ErrorCode.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/common/exception/ExceptionDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/common/exception/StudyGroupBoardCommentGlobalExceptionHandler.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/config/MybatisConfiguration.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/controller/StudyGroupBoardCommentController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/dto/StudyGroupBoardCommentDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/repository/StudyGroupBoardCommentMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/service/StudyGroupBoardCommentService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/service/StudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/common/ResponseDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/common/exception/CommonException.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/common/exception/ErrorCode.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/common/exception/ExceptionDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/common/exception/StudyGroupBoardReplyGlobalExceptionHandler.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardcomment/query/repository/StudyGroupBoardCommentMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/command/application/service/StudyGroupBoardServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardcomment/query/service/StudyGroupBoardCommentServiceTests.java
Labels: enhancement

#180 Feat: 스터디그룹 자유게시판 댓글 작성,수정,삭제 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/controller/StudyGroupBoardCommentController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/AppStudyGroupBoardCommentService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/AppStudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/domain/service/DomainStudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/StudyGroupBoardCommentServiceTests.java
Labels: enhancement

#189 Feat: 스터디그룹 자유게시판 대댓글 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/service/AppStudyGroupBoardCommentServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/controller/StudyGroupBoardReplyController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/dto/StudyGroupBoardReplyDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/service/AppStudyGroupBoardReplyService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/service/AppStudyGroupBoardReplyServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/RestStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/StudyGroupBoardReply.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/vo/RequestStudyGroupBoardReplyVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/vo/ResponseStudyGroupBoardReplyVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/repository/StudyGroupBoardReplyRepository.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/service/DomainStudyGroupBoardReplyService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/service/DomainStudyGroupBoardReplyServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/config/MybatisConfiguration.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/controller/StudyGroupBoardReplyController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/dto/StudyGroupBoardReplyDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/repository/StudyGroupBoardReplyMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/service/StudyGroupBoardReplyService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/service/StudyGroupBoardReplyServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/command/infrastructure/service/InfraStudyGroupCategoryService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/command/infrastructure/service/InfraStudyGroupCategoryServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/command/infrastructure/service/InfraStudyGroupMemberService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/command/infrastructure/service/InfraStudyGroupMemberServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/command/infrastructure/service/InfraStudyGroupNoticeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/command/infrastructure/service/InfraStudyGroupNoticeServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardreply/query/repository/StudyGroupBoardReplyMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardreply/command/application/service/StudyGroupBoardReplyServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardreply/query/service/StudyGroupBoardReplyServiceTests.java
Labels: enhancement

#190 Refactor: @PathVariable 명시적으로 작성 및 @JsonProperty 추가
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/controller/ChoiceController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/dto/ChoiceDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/domain/aggregate/vo/ProblemVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/query/config/MybatisConfiguration.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/query/controller/ChoiceController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/controller/ProblemController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/dto/ProblemDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/vo/ScheduleParticipantVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/vo/ScheduleVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/controller/ProblemController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/SubmittedAnswerPK.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/domain/repository/SubmittedAnswerRepository.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/controller/SubmittedAnswerController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/dto/SubmittedAnswerDTO.java
Labels: enhancement

#199 Feat: 스터디그룹 자유게시판 좋아요 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/application/controller/StudyGroupBoardLikeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/application/dto/StudyGroupBoardLikeDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/application/service/AppStudyGroupBoardLikeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/application/service/AppStudyGroupBoardLikeServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/aggregate/RestStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/aggregate/StudyGroupBoardLike.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/aggregate/StudyGroupBoardLikePK.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/aggregate/vo/RequestStudyGroupBoardLikeVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/aggregate/vo/ResponseStudyGroupBoardLikeVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/repository/StudyGroupBoardLikeRepository.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/service/DomainStudyGroupBoardLikeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/domain/service/DomainStudyGroupBoardLikeServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/common/ResponseDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/common/exception/CommonException.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/common/exception/ErrorCode.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/common/exception/ExceptionDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/common/exception/StudyGroupBoardLikeGlobalExceptionHandler.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/config/MybatisConfiguration.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/controller/StudyGroupBoardLikeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/dto/StudyGroupBoardLikeDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/repository/StudyGroupBoardLikeMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/service/StudyGroupBoardLikeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/query/service/StudyGroupBoardLikeServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardlike/query/repository/StudyGroupBoardLikeMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardlike/command/application/service/StudyGroupBoardLikeServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboardlike/query/service/StudyGroupBoardLikeServiceTests.java
Labels: enhancement

#200 좋아요 기능 관련 수정 사항
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/controller/RecruitmentBoardLikeController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/service/RecruitmentBoardLikeCommandService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/service/RecruitmentBoardLikeServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/common/exception/ErrorCode.java
Labels: enhancement

#201 Refactor: 스터디그룹 자유게시판 대댓글 삭제 기능 수정
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/command/application/controller/StudyGroupBoardCommentController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardlike/command/application/controller/StudyGroupBoardLikeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/controller/StudyGroupBoardReplyController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/dto/StudyGroupBoardReplyDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/application/service/AppStudyGroupBoardReplyServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/StudyGroupBoardReply.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/StudyGroupBoardReplyStatus.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/vo/RequestStudyGroupBoardReplyVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/aggregate/vo/ResponseStudyGroupBoardReplyVO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/service/DomainStudyGroupBoardReplyService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/command/domain/service/DomainStudyGroupBoardReplyServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/dto/StudyGroupBoardReplyDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/command/application/controller/StudyGroupCategoryController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupcategory/query/controller/StudyGroupCategoryController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardreply/query/repository/StudyGroupBoardReplyMapper.xml
Labels: enhancement

#203 Feat: 스터디그룹 자유게시판 내용으로 조회 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceTests.java
Labels: enhancement

#205 좋아요 및 일부 에러코드 추가
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/aggregate/RecruitmentBoard.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/service/RecruitmentBoardCommentCommandServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/service/RecruitmentBoardLikeServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/common/exception/ErrorCode.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/command/application/controller/RecruitmentBoardReplyController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/command/application/service/RecruitmentBoardReplyService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/command/application/service/RecruitmentBoardReplyServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/controller/RecruitmentBoardReplyController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/service/RecruitmentBoardReplyService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.xml
Labels: bug, enhancement

#206 Fix: 좋아요, 좋아요 취소 시 게시글 좋아요 수 변경되게 수정
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/application/service/AppStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/infrastructure/service/InfraStudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/command/infrastructure/service/InfraStudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/command/application/service/StudyGroupBoardServiceTests.java
Labels: bug, enhancement

#211 Feat: 스터디그룹 공지사항 제목,내용으로 조회 기능 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupcategory/query/service/StudyGroupCategoryTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#218 [주관식 기능 추가] 변경된 DB모델링에 맞춰서 Aggregate 수정 및 채점 기능 수정
  MSA/Schedule/src/main/java/com/springcooler/sgma/SgmaApplication.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/domain/service/ChoiceService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/choice/command/infrastructure/service/ChoiceService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/config/FeignClientConfig.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/controller/ProblemController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/dto/ProblemAndChoiceDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/dto/ProblemDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/entity/Problem.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/entity/ProblemType.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/entity/ProblemVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/vo/ScheduleParticipantVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/vo/ScheduleVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/InfraProblemServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/common/ResponseMessage.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/controller/ProblemController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/dto/ProblemAndChoiceDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/dto/ProblemDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/dto/ProblemVO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/repository/ProblemMapper.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/service/ProblemService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/problem/query/service/ProblemServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/dto/SubmittedAnswerDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/AnswerStatus.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/SubmittedAnswer.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/InfraSubmittedAnswerServiceImpl.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/OpenAIClient.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/controller/SubmittedAnswerController.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/dto/SubmittedAnswerDTO.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/repository/SubmittedAnswerMapper.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerService.java
  MSA/Schedule/src/main/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerServiceImpl.java
  MSA/Schedule/src/main/resources/com/springcooler/sgma/problem/query/repository/ProblemMapper.xml
  MSA/Schedule/src/main/resources/com/springcooler/sgma/submittedanswer/query/repository/SubmittedAnswerMapper.xml
  MSA/Schedule/src/test/java/com/springcooler/sgma/choice/command/application/service/AppChoiceServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/choice/query/service/ChoiceServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/problem/query/service/ProblemServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/submittedanswer/command/application/service/AppSubmittedAnswerServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceTests.java
  MSA/Schedule/src/test/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerServiceTests.java
  Monolithic/.gradle/8.5/executionHistory/executionHistory.lock
  Monolithic/.gradle/8.5/fileHashes/fileHashes.bin
  Monolithic/.gradle/8.5/fileHashes/fileHashes.lock
  Monolithic/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Monolithic/.gradle/buildOutputCleanup/outputFiles.bin
Labels: enhancement

#223 Feat: 스터디그룹 자유게시판 페이지네이션 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceTests.java
Labels: enhancement

#226 Feat: 스터디그룹 공지사항 페이지네이션 구현
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/command/domain/repository/StudyGroupRepository.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/common/exception/ErrorCode.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/dto/PageDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/dto/PageDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#231 모집글 조회 기능 추가
  MSA/Recruitment/src/main/java/com/springcooler/sgma/SgmaApplication.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/PaginatedResponse.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/controller/RecruitmentBoardCommentCommandController.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#233 Feat: 내가 가입한 스터디그룹 전체 조회 기능 추가
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/dto/MyStudyGroupDTO.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceTests.java
Labels: enhancement

#235 Feat : 카테고리 ID로 스터디 모집글 조회 #234
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/application/dto/RecruitmentBoardCommandDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/aggregate/RecruitmentBoard.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
  MSA/Recruitment/src/test/java/com/springcooler/sgma/recruitmentboard/query/service/StudyGroupApplicantServiceTests.java
Labels: enhancement

#239 이메일 API 쿨다운 기능 및 아이디찾기, 비번찾기 이메일 인증 수정
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/dto/EmailVerificationUserIdRequestDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/dto/EmailVerificationUserPasswordRequestDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/EmailVerificationService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/RequestResistUserVO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/repository/UserRepository.java
  MSA/User/src/main/java/com/springcooler/sgma/user/common/exception/ErrorCode.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/dto/RequestUserAuthIdDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/repository/UserMapper.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/service/UserService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/service/UserServiceImpl.java
  MSA/User/src/main/java/com/springcooler/sgma/user/security/CustomAuthenticationFailureHandler.java
  MSA/User/src/main/resources/com/springcooler/sgma/user/query/repository/UserMapper.xml
Labels: enhancement

#240 Feat: 네이버,카카오 로그인 기능 추가
  MSA/User/src/main/java/com/springcooler/sgma/config/AppConfiguration.java
  MSA/User/src/main/java/com/springcooler/sgma/config/OAuthProperties.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/dto/AuthTokens.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/OAuth2LoginService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/OAuthProvider.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/kakao/KakaoAuthorizationCode.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/kakao/KakaoUser.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/naver/NaverAuthorizationCode.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/naver/NaverUser.java
  MSA/User/src/main/java/com/springcooler/sgma/user/security/JwtUtil.java
Labels: enhancement

#242 Refactor: 카카오,네이버, 일반 로그인시 accessToken 응답body롤 수정
  MSA/User/src/main/java/com/springcooler/sgma/config/OAuthProperties.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/dto/AuthTokens.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/OAuth2LoginService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/login/AuthTokens.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/login/RequestLoginVO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/login/ResponseNormalLoginVO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/domain/aggregate/vo/login/ResponseOAuthLoginVO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/security/AuthenticationFilter.java
  MSA/User/src/main/java/com/springcooler/sgma/user/security/JwtUtil.java
Labels: enhancement

#245 Feat : 인기게시글 조회 #244
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#246 Feat: 스터디그룹 자유게시판에 작성자 조회 추가
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/dto/StudyGroupBoardDTO.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
Labels: enhancement

#247 Fix: 다른 스터디그룹 게시물이 조회되던 오류 수정
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/controller/StudyGroupBoardController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceImpl.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeService.java
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceImpl.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboard/query/repository/StudyGroupBoardMapper.xml
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.xml
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupboard/query/service/StudyGroupBoardServiceTests.java
  MSA/Group/src/test/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceTests.java
Labels: bug, enhancement

#248 Feat: 게이트웨이 CORS Web Filter 추가
  MSA/Gateway/src/main/java/com/springcooler/sgma/config/GatewayConfig.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
Labels: enhancement

#249 Refactor: 사용자 id 입력오류시 에러메시지 반환 수정
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  MSA/User/src/main/java/com/springcooler/sgma/user/security/CustomAuthenticationFailureHandler.java
Labels: enhancement

#250 Refactor: 댓글 DTO에 닉네임 추가
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardcomment/query/dto/StudyGroupBoardCommentDTO.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardcomment/query/repository/StudyGroupBoardCommentMapper.xml
Labels: enhancement

#251 Refactor: 대댓글 DTO에 닉네임 추가
  MSA/Group/src/main/java/com/springcooler/sgma/studygroupboardreply/query/dto/StudyGroupBoardReplyDTO.java
  MSA/Group/src/main/resources/com/springcooler/sgma/studygroupboardreply/query/repository/StudyGroupBoardReplyMapper.xml
Labels: enhancement

#252 Refactor: Get 요청시 RequestParam으로 호출
  MSA/User/src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
Labels: enhancement

#253 Refactor: 사용자가 작성한 댓글 목록 응답 형식 수정
  MSA/Gateway/src/main/java/com/springcooler/sgma/config/GatewayConfig.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/dto/BooleanResponseDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/dto/RequestNicknameDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/dto/RequestUserAuthIdentifierDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/dto/RequestUserIdentifierDTO.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/service/UserService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/query/service/UserServiceImpl.java
Labels: enhancement

#254 Feat : 모집글 조회 내용 추가 #1
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#255 Refactor: 모집글 등록시 수정사항
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandServiceImpl.java
Labels: bug

#256 Feat : 그룹Id 모집글 조회 내용 추가 #130
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#257 Feat : 시간순 정렬 #130
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#260 Feature/recruitment board
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboard/query/repository/RecruitmentBoardMapper.xml
Labels: enhancement

#258 Refactor: 회원 재활성화 기능 수정
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  MSA/User/src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTests.java
Labels: enhancement

#261 Feat : 페이지네이션 취소
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
Labels: enhancement

#264 Feature/recruitment board
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/controller/StudyGroupApplicantController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/dto/StudyGroupApplicantDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/studygroupapplicant/query/service/StudyGroupApplicantService.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.xml
Labels: enhancement

#266 Refactor: 서버 빌드를 위한 테스트 코드 수정
  MSA/User/src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTests.java
  MSA/User/src/test/java/com/springcooler/sgma/user/query/service/RecruitmentCommentServiceImplTests.java
  MSA/User/src/test/java/com/springcooler/sgma/user/query/service/UserServiceImplTests.java
Labels: enhancement

#268 Feature/recruitment board
  MSA/Recruitment/src/main/java/com/springcooler/sgma/SgmaApplication.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/repository/RecruitmentBoardRepository.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/controller/RecruitmentBoardCommentCommandController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/service/RecruitmentBoardCommentCommandService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/command/application/service/RecruitmentBoardCommentCommandServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardcomment/query/dto/RecruitmentBoardCommentDTO.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardreply/query/dto/RecruitmentBoardReplyDTO.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardcomment/query/repository/RecruitmentBoardCommentMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.xml
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.xml
Labels: enhancement

#269 Fix: 좋아요 추가, 취소 이슈 해결
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/aggregate/RecruitmentBoard.java
Labels: bug

#272 Fix: 오타 수정
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  MSA/Recruitment/src/main/resources/com/springcooler/sgma/recruitmentboardreply/query/repository/RecruitmentBoardReplyMapper.xml
Labels: bug, enhancement

#271 Feat: 소셜 회원가입시 생성시각 필드 세팅 추가
  MSA/User/src/main/java/com/springcooler/sgma/user/command/application/service/OAuth2LoginService.java
Labels: enhancement

#273 Fix : 좋아요 취소 기능 수정
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/controller/RecruitmentBoardLikeController.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/service/RecruitmentBoardLikeCommandService.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/application/service/RecruitmentBoardLikeServiceImpl.java
  MSA/Recruitment/src/main/java/com/springcooler/sgma/recruitmentboardlike/command/domain/repository/RecruitmentBoardLikeRepository.java
Labels: enhancement
