Repository Spring-Cooler/SGMA_Backend, pull requests merged in 2024-08, with the labels that each got.

#9 Feat: 스터디 그룹원 API
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/config/StudyGroupMemberAppConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMember.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMemberStatus.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/repository/StudyGroupMemberRepository.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/service/DomainStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/service/DomainStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/service/StudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/infrastructure/service/InfraStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/config/StudyGroupMemberMybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/dto/StudyGroupMemberDTO.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceImpl.java
  src/main/resources/com/springcooler/sgma/studygroupmember/StudyGroupMemberMapper.xml
  src/main/resources/com/springcooler/sgma/studygroupmember/query/repository/StudyGroupMemberMapper.xml
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceTests.java
Labels: enhancement

#11 Feat: 스터디 그룹 API 관련
  src/main/java/com/springcooler/sgma/config/AppConfiguration.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/dto/StudyGroupDTO.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/StudyGroup.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/StudyGroupStatus.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/repository/StudyGroupRepository.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/service/DomainStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/service/DomainStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/service/StudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/StudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studygroup/query/config/StudyGroupMybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/query/dto/StudyGroupDTO.java
  src/main/java/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.java
  src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceImpl.java
  src/main/resources/com/springcooler/sgma/studygroup/StudyGroupMapper.xml
  src/main/resources/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.xml
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceTests.java
Labels: enhancement

#36 Feat: 스터디 그룹 참가 신청 승인 및 그룹 탈퇴 API
  src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/infrastructure/service/InfraStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/infrastructure/service/InfraStudyGroupMemberServiceImpl.java
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
Labels: enhancement

#38 Fix: PUT API 주석 처리
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
Labels: invalid

#39 Test: 스터디 그룹 이름 변경 테스트코드 추가
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
Labels: enhancement

#40 Feature/recruitment board
  build.gradle
  src/main/java/com/springcooler/sgma/SgmaApplication.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/BoardActiveStatus.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/repository/StudyGroupApplicantRepository.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/common/Template.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/controller/StudyGroupApplicantController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/dto/StudyGroupApplicantDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/service/StudyGroupApplicantService.java
  src/main/resources/com/springcooler/sgma/studygroupapplicant/StudyGroupApplicantMapper.xml
  src/main/resources/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.xml
  src/test/java/com/springcooler/sgma/studygroupapplicant/query/service/StudyGroupApplicantServiceTests.java
Labels: enhancement

#49 Feat: 스터디그룹 공지사항 조회 기능 구현
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/dto/StudyGroupNoticeDTO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/StudyGroupNotice.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/StudyGroupNoticeStatus.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/repository/StudyGroupNoticeRepository.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/service/DomainStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/service/DomainStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/infrastructure/service/InfraStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/infrastructure/service/InfraStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/common/ResponseMessage.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/config/StudyGroupNoticeMybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/dto/StudyGroupNoticeDTO.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceImpl.java
  src/main/resources/com/springcooler/sgma/studygroupnotice/query/repository/StudyGroupNoticeMapper.xml
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/query/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#42 Feat: 스터디 그룹 카테고리 변경 API 추가
  src/main/java/com/springcooler/sgma/studygroup/command/application/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/controller/StudyGroupMemberController.java
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
Labels: enhancement

#50 Feat: 스터디그룹 공지사항 생성 API 구현
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/service/DomainStudyGroupNoticeService.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/service/DomainStudyGroupNoticeServiceImpl.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#65 Test: 테스트 코드 수정
  src/test/java/com/springcooler/sgma/studygroup/command/application/service/StudyGroupServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupmember/command/application/service/StudyGroupMemberServiceTests.java
  src/test/java/com/springcooler/sgma/studygroupnotice/command/application/service/StudyGroupNoticeServiceTests.java
Labels: enhancement

#68 Refactor: 스터디그룹, 그룹원, 공지사항, 카테고리 조회 컨트롤러 코드 리팩토링
  src/main/java/com/springcooler/sgma/studygroup/query/controller/StudyGroupController.java
  src/main/java/com/springcooler/sgma/studygroupcategory/query/controller/StudyGroupCategoryController.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/controller/StudyGroupNoticeController.java
Labels: enhancement

#70 Fix : bean 충돌 문제 해결
  src/main/java/com/springcooler/sgma/problem/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantCommandController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/controller/StudyGroupApplicantController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantCommandDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/repository/StudyGroupApplicantRepository.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/service/StudyGroupApplicantDomainService.java
  src/main/java/com/springcooler/sgma/user/config/MybatisConfiguration.java
Labels: bug

#72 Feat : testCode 작성완료 #41
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantCommandDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
  src/test/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceTests.java
Labels: enhancement

#75 Feat: 응답 형식 및 에러 핸들러 기능 추가
  src/main/java/com/springcooler/sgma/user/common/ResponseDTO.java
  src/main/java/com/springcooler/sgma/user/common/exception/CommonException.java
  src/main/java/com/springcooler/sgma/user/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/user/common/exception/ExceptionDTO.java
  src/main/java/com/springcooler/sgma/user/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#76 Feature/study problem
  src/main/java/com/springcooler/sgma/problem/command/application/controller/ProblemController.java
  src/main/java/com/springcooler/sgma/problem/command/application/dto/ProblemDTO.java
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/command/application/service/ProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/domain/aggregate/Problem.java
  src/main/java/com/springcooler/sgma/problem/command/domain/repository/ProblemRepository.java
  src/main/java/com/springcooler/sgma/problem/command/domain/service/DomainProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/domain/service/DomainProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/DomainProblemService.java
  src/main/java/com/springcooler/sgma/problem/command/infrastructure/service/DomainProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/query/controller/ProblemController.java
  src/main/java/com/springcooler/sgma/problem/query/repository/ProblemMapper.java
  src/main/java/com/springcooler/sgma/problem/query/service/ProblemService.java
  src/main/java/com/springcooler/sgma/problem/query/service/ProblemServiceImpl.java
  src/main/resources/com/springcooler/sgma/problem/query/repository/ProblemMapper.xml
  src/test/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceTests.java
  src/test/java/com/springcooler/sgma/problem/query/service/ProblemServiceTests.java
Labels: enhancement

#79 Style: 코드 주석 추가, 코드 스타일 변경
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/command/application/service/AppStudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/StudyGroup.java
  src/main/java/com/springcooler/sgma/studygroup/command/domain/aggregate/StudyGroupStatus.java
  src/main/java/com/springcooler/sgma/studygroup/command/infrastructure/service/InfraStudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroup/query/repository/StudyGroupMapper.java
  src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupService.java
  src/main/java/com/springcooler/sgma/studygroup/query/service/StudyGroupServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupcategory/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/controller/StudyGroupMemberController.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberService.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/application/service/AppStudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMember.java
  src/main/java/com/springcooler/sgma/studygroupmember/command/domain/aggregate/StudyGroupMemberStatus.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studygroupmember/query/service/StudyGroupMemberServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/controller/StudyGroupNoticeController.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/application/service/AppStudyGroupNoticeServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupnotice/command/domain/aggregate/StudyGroupNoticeStatus.java
  src/main/java/com/springcooler/sgma/studygroupnotice/query/config/MybatisConfiguration.java
Labels: documentation

#80 Feat: 테스트 환경에서도 롬복 적용 라이브러리 추가
  build.gradle
  src/main/resources/com/springcooler/sgma/user/UserMapper.xml
  src/main/resources/com/springcooler/sgma/user/query/repository/UserMapper.xml
Labels: enhancement

#81 Refactor: Exception handler 주석
  src/main/java/com/springcooler/sgma/user/common/ResponseDTO.java
  src/main/java/com/springcooler/sgma/user/common/exception/CommonException.java
  src/main/java/com/springcooler/sgma/user/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/user/common/exception/ExceptionDTO.java
  src/main/java/com/springcooler/sgma/user/common/exception/GlobalExceptionHandler.java
  src/main/java/com/springcooler/sgma/user/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/query/dto/UserDTO.java
  src/main/java/com/springcooler/sgma/user/query/repository/UserMapper.java
  src/main/java/com/springcooler/sgma/user/query/service/UserService.java
  src/main/java/com/springcooler/sgma/user/query/service/UserServiceImpl.java
  src/main/resources/com/springcooler/sgma/user/query/repository/UserMapper.xml
  src/test/java/com/springcooler/sgma/user/query/service/UserServiceImplTests.java
Labels: documentation

#84 Feature/study problem 제출 답안 단순 조회
  src/main/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceImpl.java
  src/main/java/com/springcooler/sgma/problem/query/controller/ProblemController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/controller/SubmittedAnswerController.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/application/dto/SubmittedAnswerDTO.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/SubmittedAnswer.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/aggregate/SubmittedAnswerPK.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/domain/repository/SubmittedAnswerRepository.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceImpl.java
  src/main/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/SubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/config/MybatisConfiguration.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/controller/SubmittedAnswerController.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/dto/SubmittedAnswerDTO.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/repository/SubmittedAnswerMapper.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerService.java
  src/main/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerServiceImpl.java
  src/main/resources/com/springcooler/sgma/submittedanswer/SubmittedAnswerMapper.xml
  src/main/resources/com/springcooler/sgma/submittedanswer/query/repository/SubmittedAnswerMapper.xml
  src/test/java/com/springcooler/sgma/problem/command/application/service/AppProblemServiceTests.java
  src/test/java/com/springcooler/sgma/submittedanswer/command/infrastructure/service/AppSubmittedAnswerServiceTests.java
  src/test/java/com/springcooler/sgma/submittedanswer/query/service/SubmittedAnswerServiceTests.java
Labels: enhancement

#86 Feat: 회원이 작성한 댓글및 대댓글 조회 기능 추가
  src/main/java/com/springcooler/sgma/user/common/exception/ErrorCode.java
  src/main/java/com/springcooler/sgma/user/query/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/query/dto/RecruitmentBoardCommentDTO.java
  src/main/java/com/springcooler/sgma/user/query/dto/RecruitmentBoardReplyDTO.java
  src/main/java/com/springcooler/sgma/user/query/dto/UserCommentsAndRepliesDTO.java
  src/main/java/com/springcooler/sgma/user/query/repository/RecruitmentCommentMapper.java
  src/main/java/com/springcooler/sgma/user/query/service/RecruitmentCommentService.java
  src/main/java/com/springcooler/sgma/user/query/service/RecruitmentCommentServiceImpl.java
  src/main/java/com/springcooler/sgma/user/query/service/UserService.java
  src/main/java/com/springcooler/sgma/user/query/service/UserServiceImpl.java
  src/main/resources/com/springcooler/sgma/user/query/repository/RecruitmentCommentMapper.xml
  src/test/java/com/springcooler/sgma/user/query/service/RecruitmentCommentServiceImplTests.java
Labels: enhancement

#85 Feature/study shedule
  src/main/java/com/springcooler/sgma/studyschedule/query/config/StudyScheduleParticipantMybatisConfiguration.java
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/controller/StudyScheduleParticipantController.java
  src/main/java/com/springcooler/sgma/studyschedule/query/dto/StudyScheduleParticipantDTO.java
  src/main/java/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleMapper.java
  src/main/java/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleParticipantMapper.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleParticipantService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleParticipantServiceImpl.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleService.java
  src/main/java/com/springcooler/sgma/studyschedule/query/service/StudyScheduleServiceImpl.java
  src/main/resources/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleMapper.xml
  src/main/resources/com/springcooler/sgma/studyschedule/query/repository/StudyScheduleParticipantMapper.xml
Labels: enhancement

#89 Fix: 스터디 그룹 지원 조회 #88
  src/main/java/com/springcooler/sgma/SgmaApplication.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/controller/RecruitmentBoardCommandController.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/dto/RecruitmentBoardCommandDTO.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandService.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/domain/aggregate/RecruitmentBoard.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/controller/RecruitmentBoardController.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/dto/RecruitmentBoardDTO.java
  src/main/java/com/springcooler/sgma/recruitmentboard/query/service/RecruitmentBoardService.java
  src/main/java/com/springcooler/sgma/recruitmentboardlike/command/domain/aggregate/RecruitmentBoardLike.java
  src/main/java/com/springcooler/sgma/recruitmentboardlike/command/domain/aggregate/RecruitmentBoardLikeId.java
  src/main/java/com/springcooler/sgma/recruitmentboardlike/query/service/RecruitmentBoardLikeService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/ApplicationStatus.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/common/Template.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/controller/StudyGroupApplicantController.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/dto/StudyGroupApplicantDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/query/service/StudyGroupApplicantService.java
  src/main/resources/com/springcooler/sgma/recruitmentboardlike/query/repository/RecruitmentBoardLikeMapper.xml
  src/main/resources/com/springcooler/sgma/studygroupapplicant/query/repository/StudyGroupApplicantMapper.xml
Labels: enhancement

#90 Feat: 회원 탈퇴 및 활성화 기능 추가
  src/main/java/com/springcooler/sgma/user/command/application/controller/UserController.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserService.java
  src/main/java/com/springcooler/sgma/user/command/application/service/UserServiceImpl.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/AcceptStatus.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/ActiveStatus.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/SignupPath.java
  src/main/java/com/springcooler/sgma/user/command/domain/aggregate/UserEntity.java
  src/main/java/com/springcooler/sgma/user/command/domain/repository/UserRepository.java
  src/test/java/com/springcooler/sgma/user/command/application/service/UserServiceImplTest.java
Labels: enhancement

#93 Feature/study group applicant
  src/main/java/com/springcooler/sgma/SgmaApplication.java
  src/main/java/com/springcooler/sgma/recruitmentboard/command/application/service/RecruitmentBoardCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/dto/StudyGroupApplicantCommandDTO.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandService.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/application/service/StudyGroupApplicantCommandServiceImpl.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/aggregate/StudyGroupApplicant.java
  src/main/java/com/springcooler/sgma/studygroupapplicant/command/domain/repository/StudyGroupApplicantRepository.java
Labels: bug, enhancement
